# Handling Numerical Data

In [2]:
import numpy as np
from sklearn import preprocessing

# Feature Scaling / Normalization

### Reasons for Feature Scaling include:-

#### Improved Convergence.
- Algorithms like gradient descent converge faster when features are scaled, unscaled features cause gradients to be very different in magnitude, leading to zigzag paths towards the minimum during oprimization.

#### Equal Treatment of Features:
- Algorithms such as KNN and SVMs are sensitive allowing for larger scales to disproportionately influence the results, leading to biased models.
- Rescaling ensures that each feature contributes equally to the model.

#### Enhanced Model Interpretability:
- Model coefficients and weights can be more easily interpreted as they correspond to features of similar magnitude.

#### Stabilized Training:
- Neural Networks v=benefit from feature scaling as it helps prevent the network from becoming unstable due to large values in the input data.

#### Compatibility with Regularizatio:
- Regularization techniques like Lasso / rigde regression are affected by feature scales, regularization ensures tha regularization penalties are applied uniformly across all features.

- Common rescaling methods include min-ma scaling, z-score normalization and max-abs scaling.

### Min-Max

In [3]:
# we will create a feature.
feature = np.array([[-500.5],
                    [-100.0],
                    [0],
                    [100.1],
                    [900.9]])

# create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1)) 
# goal of the Min-Max scaling is to transform the features so they are within a specific range i.e (0, 1) in this case.

# Scaling he feature.
scaled_feature = minmax_scale.fit_transform(feature)
# if we used fit only the min and max calculations would have been done and stores separately.
# the transform is then used to change the original values and rescale them
# fit_transform does both at the same time.

scaled_feature

array([[0.        ],
       [0.28578564],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### Z-Score / Standard Scaling

In [4]:
# Standardizing a Feature / Z-score.

x = np.array([[-1000.1],
[-200.2],
[500.5],
[600.6],
[9000.9]])

# Create scaler
scaler = preprocessing.StandardScaler()
# features will have a mean of 0 and a standard deviation of 1.

# Transform the feature
standardized = scaler.fit_transform(x)

# Show feature
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [5]:
# Print mean and standard deviation
print("Mean:", round(standardized.mean()))
print("Standard deviation:", standardized.std())


Mean: 0
Standard deviation: 1.0


- Standard Scaler works best for PCA but neural networks are better of with min-max.

### Robust Scaler

In [6]:
# Similar to standard scaler only it uses the median and the quartile range to counter the negative effects of significant outliers.

# Create scaler
robust_scaler = preprocessing.RobustScaler()

# Transform feature
rubust = robust_scaler.fit_transform(x)


rubust

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])